---

- name: N8N | Create directories
  file:
    name: /opt/n8n/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: N8N | Create a volume
  containers.podman.podman_volume:
    state: present
    name: n8n-vol
    label:
      owner: n8n
      app: n8n
    options:
      - "o=uid=1000,gid=0"
      - "device=tmpfs"
      - "type=tmpfs"

- name: N8N | Start the container
  containers.podman.podman_container:
    name: n8n-app
    image: n8nio/n8n:{{ n8n_version }}
    pod: n8n
    volume:
      - n8n-vol:/home/node/.n8n
